apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Django настройки
  DEBUG: "False"
  ALLOWED_HOSTS: "star-burger.test,localhost,127.0.0.1"
  POSTGRES_DB: "test_k8s"
  POSTGRES_USER: "test_k8s"
